# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 06 Dec 2020 17:04:01 +0000
*               @ALL          0
*               @user         8
