<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: luispzmarin
 * Date: Sun, 06 Dec 2020 21:21:09 +0000
 */

$conf['title'] = 'LuisPzMarin Wiki';
$conf['lang'] = 'es';
$conf['template'] = 'bootstrap3';
$conf['license'] = '0';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['fullpath'] = 1;
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['tpl']['bootstrap3']['bootstrapTheme'] = 'bootswatch';
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'paper';
$conf['tpl']['bootstrap3']['showThemeSwitcher'] = 1;
$conf['tpl']['bootstrap3']['socialShareProviders'] = 'facebook,linkedin,pinterest,whatsapp,reddit,twitter,telegram,yammer,google-plus';
$conf['tpl']['white']['tocPosition'] = 'dokuwiki';
$conf['tpl']['white']['footer'] = 'Luis Pz Marín';
$conf['tpl']['sprintdoc']['sidebar_sections'] = 'li.level1 > .li';
$conf['tpl']['sprintdoc']['header_layout'] = 'header-compact';
$conf['tpl']['argon-alternative']['showIcon'] = '0';
$conf['tpl']['mindthedark']['theme'] = 'dark';
