# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Sun, 06 Dec 2020 17:04:01 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

luispzmarin:$2y$10$RJty3ILPZkTtrDuG51Da5us719QzkOV/IzZC7tmT7FbWCWCr7yfzO:Luis Pérez Marín:luispzmarin@gmail.com:admin,user
